language: node_js
sudo: false
node_js:
- 6
- 7
cache:
  directories:
  - node_modules
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run release
deploy:
  provider: npm
  skip_cleanup: true
  email: qowera@qq.com
  api_key:
    secure: oyO4q6gmjPedl6XI5XMNs9wohA0x9xyt6t4jYpzWNcgVlvXzMVVEvV3cxZectU9fyt2+kuI3nx4VSGY1mymY4hm/BXmhRl83bgMAz+jeBYR2ef9qCMklPd+6oX1dcb0iOFdscaTKU18NBiSJbSTLLNeTZHWzWxxXlaclDRusMKoKtLHB8sLa/AssDVmWJqPXmiWqbp7f0CQieCNzZYrYw9nqrfb1mjfLvfK4FS3UvRH49F/CkVlt3kb30RTLg/rhrTF/5rEltWa6nhlDMq2wH8wYo5tOzwcrwa6K7ytZ6ziMfprnmdoYGCek7j298ZNOMqmuH1m9yi9arO4LXib/wvgod5ZQ5oofbPEjTmhmoBc2WfDv0qYBdqhd66oNGDriQ/OlnH42etDGYHulrUiErMQyFTBP1bs5uzvYacGUvvj9XOdi1v58lafPhkYACO0iHy1bHjp4ynCZ8vX1oJC1RDOvi9AoXJsUcj0+tuGZ91y9yhuaQ0AYyBKCcmSMkhuxMRJoAMm9plAqVcnWckIE9K6HT/D8MKAQ6xmTziSfFIskZtlNcpkRGdAVtNu8BVCXNvTvZNwaocMFOwctcvFpcbjbStHVb0wkw/fz3q08OymgNoRwChr4wFtegYz3os594XGp2QMLwXJ/KrBeMLsHRXd1FI4Riot3ZqNGPmuYVNg=
  on:
    tags: true
    repo: DavidKk/bloke-theme-sharp
